nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: swr.cn-east-3.myhuaweicloud.com/kweaver-ai/agent-observability
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

opensearch:
  endpoint: http://opensearch-read.resource.svc.cluster.local:9200
  traceIndex: ss4o_traces-default-namespace
  auth:
    enabled: false
    username: ""
    password: ""
